name: InvSee
version: 1.0-Release
main: de.blaumeise03.invSee.InvSee
description: A invSee plugin.
api-version: 1.13
author: Blaumeise03
website: http://blaumeise03.de/


commands:
  invSee:
    description: Shows the Inventory of a Player and modify it.
  enderSee:
    description: Shows the EnderChest of a Player and modify it.
permissions:
  invSee.invSee:
    description: Permission for InvSee
    default: op
  invSee.enderSee:
    description: Permission for EnderSee
    default: op
  invSee.*:
    description: Wildcard
    default: op
    children:
      invsee.invSee: true
      invsee.enderSee: true